services:
    # core exception listener
    core_exception_listener:
        class: AppBundle\Listener\CoreExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onCoreException, priority: 1000 }

    app.twig_extension:
        class: AppBundle\Helper\TwigExtension
        public: false
        tags:
            - { name: twig.extension }

    decks:
        class: AppBundle\Services\Decks
        arguments: ["@doctrine.orm.entity_manager", "@deck_validation_helper", "@diff", "@logger"]

    texts:
        class: AppBundle\Services\Texts
        arguments: ["%kernel.root_dir%"]

    diff:
        class: AppBundle\Services\Diff
        arguments: ["@doctrine.orm.entity_manager"]

    cards_data:
        class: AppBundle\Services\CardsData
        arguments: ["@doctrine", "@request_stack", "@router", "@templating.helper.assets", "%kernel.root_dir%"]

    decklist_manager:
        class: AppBundle\Model\DecklistManager
        shared: false
        arguments: ["@doctrine.orm.entity_manager", "@request_stack", "@router", "@logger"]

    decklist_factory:
        class: AppBundle\Model\DecklistFactory
        arguments: ["@doctrine.orm.entity_manager", "@deck_validation_helper", "@texts"]

    deck_validation_helper:
        class: AppBundle\Helper\DeckValidationHelper
        arguments: []

    fellowship_validation_helper:
        class: AppBundle\Helper\FellowshipValidationHelper
        arguments: []

    fellowship_manager:
        class: AppBundle\Model\FellowshipManager
        shared: false
        arguments: ["@doctrine.orm.entity_manager", "@request_stack", "@router", "@logger"]

    questlog_manager:
        class: AppBundle\Model\QuestLogManager
        shared: false
        arguments: ["@doctrine.orm.entity_manager", "@request_stack", "@router", "@logger"]